services:
#  auth.api:
#    image: auth.api
#    build:
#      context: .
#      dockerfile: src/Auth.Api/Dockerfile
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
